# SwiftLint configuration file

# 包含的目录
included:
  - ZHKLine/
  - ZHKLineTests/
  - ZHKLineUITests/

# 排除的目录和文件
excluded:
  - ZHKLine.xcodeproj/
  - ZHKLine/Assets.xcassets/
  - ZHKLine/Base.lproj/
  - ZHKLine/huobi_image.jpg

# 只保留强制解包检查规则
only_rules:
  - force_unwrapping

# 自定义配置
reporter: "xcode" # xcode, json, csv, checkstyle, junit, html, emoji
